export enum PathCommandName {
  None = "",
  MoveTo = "M",
  MoveToLocal = "m",
  Line = "L",
  LineLocal = "l",
  ClosePath = "Z",
  ClosePathLocal = "z",
  CubicCurve = "C",
  CubicCurveLocal = "c",
  BindCubicCurve = "S",
  BindCubicCurveLocal = "s",
  QuadraticCurve = "Q",
  QuadraticCurveLocal = "Q",
  BindQuadraticCurve = "T",
  BindQuadraticCurveLocal = "t",
  Arcs = "A",
  ArcsLocal = "a",
  HorizontalLine = "H",
  HorizontalLineLocal = "h",
  VerticalLine = "V",
  VerticalLineLocal = "v",
}
